#pragma once
#include "PiratesEngine/Core/Application.h"
#include "PiratesEngine/Core/Log.h"
#include "PiratesEngine/Core/Layer.h"
#include "PiratesEngine/ImGui/ImGuiLayer.h"
#include "PiratesEngine/Core/Input.h"
#include"PiratesEngine/Core/KeyCode.h"
#include"PiratesEngine/Core/MouseButtonCodes.h"
#include "PiratesEngine/Renderer/Renderer.h"
#include "PiratesEngine/Renderer/Renderer2D.h"
#include "PiratesEngine/Core/TimeStep.h"
#include "PiratesEngine/Renderer/Shader.h"
#include "PiratesEngine/Renderer/VertexArray.h"
#include "PiratesEngine/Renderer/OrthoGraphicCamera.h"
#include "PiratesEngine/Core/TimeStep.h"
#include "glm/gtc/matrix_transform.hpp"
#include "Platform/OpenGl/OpenGLShader.h"
#include "glm/gtc/type_ptr.hpp"
#include "PiratesEngine/Renderer/Texture.h"
#include "Platform/OpenGl/OpenGLTexture.h"
#include "PiratesEngine/Renderer/OrthoGraphicCameraController.h"
#include "imgui.h"
